
import { Navbar } from '@/components'
import './globals.css'
import { Montserrat } from 'next/font/google'


const montserrat = Montserrat({ 
  subsets: ['latin'],
  weight: ['400','600', '700'],
  style: ['normal','italic']

}
)



export const metadata = {
  title: 'Get Linked',
  description: 'Generated by BoiOctaves',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    
      <body className={`${montserrat.className}`}>{children}</body>
    
    </html>
  )
}
